# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2
jobs:
  test-verilog:
    docker:
      - image: natanvotre/verilog-machine:0.0.1
    environment:
      VENV: /opt/venv
    steps:
      - checkout
      - run: sh test.sh

workflows:
  version: 2
  test:
    jobs:
      - test-verilog
